### ISSUE TITLE
libparasail-sys error when compiling on Rust 1.76.0

### ISSUE THREAD

**Issue by davidlougheed** [nsbuitrago/parasail-rs#10]
Hello,
When I compile with Rust 1.76.0 (the only version available to me on the HPC cluster I'm using), I now get an error where I did not used to get one:

```
error[E0658]: use of unstable library feature 'offset_of'
```

This worked in 0.7.3, but updating to 0.7.5 seems to break it.

**Comment by nsbuitrago** [comment]
Hi, so sorry I accidentally introduced a breaking change from the bindgen crate. libparasail-sys is updated and 0.7.6 fixes this.

**Comment by davidlougheed** [comment]
thanks!!
